name: check_dependency

on: workflow_call

jobs:
  depCheck:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Prepare for dependency check
        run: mvn clean install -DskipTests -P ci
      - name: Analyze dependencies
        shell: bash
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn verify -Dexecution.owasp.skip=false -DnvdApiKey=$NVD_API_KEY -P ci
      - name: Archive dependency reports
        uses: actions/upload-artifact@v4
        with:
          name: OWASP dependency check report
          path: '**/target/dependency-check-report.html'
          if-no-files-found: error
          retention-days: 7