name: Check code style

on: workflow_call

jobs:
  depCheck:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Check code style
        run: mvn clean verify -DskipTests -P ci -Dexecution.checkstyle.skip=false -Dexecution.errorprone.skip=false
